# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5ohmSxI-tKxplQltKRnBoo-uWg6KqHJ
"""

import pandas as pd
import numpy as np
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from google.colab import files
file=files.upload()
df=pd.read_csv("amazon_reviews.csv")
df=df.dropna()

def convert_sentiment(rating):
  if rating <=3:
    return 'negative'
  else:
    return 'positive'
df['Sentiment']=df['rating'].apply(convert_sentiment)

print(df.columns)

def cleaning(text):
  text=re.sub(r'[^a-zA-z]',  ' ',text)
  text=text.lower()
  return text
df['review']=df['review'].apply(cleaning)

vectorizer=TfidfVectorizer(max_features=5000)
X=vectorizer.fit_transform(df['review'])
y=df['Sentiment']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=LogisticRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print('Accuracy:',accuracy_score(y_test,y_pred))

import streamlit as st
st.title("Product review sentiment analyser")
review=st.text_area("Enter your review")
if st.button("analyse") and review!=None:
  cleaned=cleaning(review)
  vector=vectorizer.transform([cleaned])
  prediction=model.predict(vector)
  st.write("Sentiment:",prediction[0])

!jupyter nbconvert --to script "Copy of Untitled6.ipynb"

!rm -rf /content/*